config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :users do
    post 'toggle_frozen_user', on: :member
  end
  resources :beers
  resources :breweries
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  delete 'signout', to: 'sessions#destroy'  
  root 'breweries#index'
  resources :places, only:[:index, :show]
  post 'places', to:'places#search'
  post 'block', to:'user#block'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings

  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 30 }
  validates :password, length: { minimum: 4 }   
  validates :password, format: { with: /([A-Z].*\d)|(\d.*[A-Z].*)/,
              message: "should contain one number and one capital letter" }   
  
  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  
  def favorite_brewery
    return nil if ratings.empty? 
    
    ratings_of_breweries = ratings.group_by { |r| r.beer.brewery }
    averages_of_breweries = []
    ratings_of_breweries.each do |brewery, ratings|
      averages_of_breweries << {
        brewery: brewery,
        rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end  
    averages_of_breweries.sort_by{ |b| -b[:rating] }.first[:brewery]
  end  

  def favorite_style
    return nil if ratings.empty? 
    
    ratings_of_styles = ratings.group_by { |r| r.beer.style }
    averages_of_styles = []
    ratings_of_styles.each do |style, ratings|
      averages_of_styles << {
        style: style,
        rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end  
    averages_of_styles.sort_by{ |b| -b[:rating] }.first[:style]
  end  

  def is_admin
    return true if admin?
    false
  end

  def is_member_of?(beer_club)
    beer_clubs.include? beer_club
  end  

    def self.most_active(n)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |u| -(u.ratings.count) }[0,n]
  end  
                
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def block
    if current_user.admin
      @user.blocked = true
      respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully blocked.' }
      format.json { head :no_content }
      end
    end
  end
  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if @user==current_user 
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  def toggle_frozen
    user = User.find(params[:id])
    user.update_attribute :blocked, (not user.blocked)

    new_status = user.blocked? ? "frozen" : "reactivated"

    redirect_to :back, notice:"user account changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Profile', user, class:'btn btn-primary' %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_user_path, class:'btn btn-primary' %>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for(@user) do |f| %>

	<div class="field">
    	<%= f.label :username %><br />
    	<%= f.text_field :username %>
  	</div>

	
  	<div class="field">
    	<%= f.label :password %><br />
    	<%= f.password_field :password %>
  	</div>
  	<div class="field">
    	<%= f.label :password_confirmation %><br />
    	<%= f.password_field :password_confirmation  %>
  	</div>
<%= f.submit %>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @user.username %> </h2>

<p>Has made <%= @user.ratings.count %> ratings</p>

<% if @user.beer_clubs.any? %>

  <p>member of
  <% @user.beer_clubs.each do |club| %>
    <%= link_to club.name, club%>
  <% end %>
  </p>
<% else %>
  <p>no beerclub memberships</p>
<% end %>

<% if @user.ratings.any? %>
  <p> Favorite beer: <%= @user.favorite_beer.name %> </p>
  <p> Favorite brewery: <%= @user.favorite_brewery.name %> </p>
  <p> Favorite style: <%= @user.favorite_style %> </p>

  <p> average rating <%= @user.average_rating %></p>

  <h3>ratings</h3>

  <ul>
  <% @user.ratings.each do |r| %>
    <li>
      <%= r %>
      <% if @user == current_user %>
        <%= link_to 'delete', r, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
  </ul>

<% end %>


<% if @user==current_user%>
  <%= link_to 'change password', edit_user_path(@user) %> <br>
  <%= link_to 'destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }  %> 
<% end %>
>

  <%= link_to "block", toggle_frozen_user_path(@user.id), method: :post, class: "btn btn-primary" %>